### ISSUE TITLE
New NPM release

### ISSUE THREAD

**Issue by rma4ok** [feathersjs-ecosystem/feathers-authentication-management#158]
Seems like the last release had happened about 3 months ago. 
There was a couple of fixes after the release and also 1 PR merged in master.
Could you please make a new NPM release based on the latest master?

**Comment by claustres** [comment]
Closed by https://github.com/feathersjs-ecosystem/feathers-authentication-management/commit/76cbd8588692ebb98cad163dd44f358374fdc742.

**Comment by rma4ok** [comment]
Thank you @claustres !
