### ISSUE TITLE
Provide a way to let resolvers hash the password

### ISSUE THREAD

**Issue by jd1378** [feathersjs-ecosystem/feathers-authentication-management#225]
Currently [password reset](https://github.com/feathersjs-ecosystem/feathers-authentication-management/blob/7b73637bb1b8204a368d11e3c9117a4a6e6f3d92/src/methods/reset-password.ts#L163) hashes the user's password before patching, which in feathers v5 is done usually in resolvers. this causes the password to be hashed two times and thus fail.

please add an option to skip hashing the password in favor of resolvers

**Comment by fratzinger** [comment]
Would you be up for a PR?

**Comment by jd1378** [comment]
of course
I'll send a PR soon
